language: python
sudo: false

matrix:
  include:
    # Linux Builds
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35

    # OSX Builds
    - language: generic
      os: osx
      env: TOXENV=py26
    - language: generic
      os: osx
      env: TOXENV=py27
    - language: generic
      os: osx
      env: TOXENV=py33
    - language: generic
      os: osx
      env: TOXENV=py34
    - language: generic
      os: osx
      env: TOXENV=py35

cache:
  - pip
  - directories:
    - ${HOME}/.cache

before_install:
  - openssl version

install:
  - chmod a+x ./.travis/install.sh ./.travis/run.sh
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - ./.travis/upload_coverage.sh

notifications:
  email: false
